language: ruby
cache: bundler
rvm:
  - 2.5.8
  - 2.6.6
  - 2.7.1
gemfile:
  - gemfile
script: "bundle exec rake spec"
notifications:
  webhooks: https://gd-radiator.ngrok.com/hubot/travis?room=devlab@conference.im.office.gdi
  on_success: change
  on_failure: always
